"""IaC Generator — produces AWS Terraform scaffold files from the mapping context."""


def generate_iac_bundle(aws_mapping: list, inventory: list) -> dict:
    """Generate an IaC bundle payload with Terraform scaffold files.

    Returns the iac_bundle dict ready for the context.
    """
    files = []
    terraform_contents = {}

    # --- Networking module ---
    networking_tf = '''# ============================================
# NovaPay AWS Landing Zone — Networking
# Generated by RADCloud Watchdog Agent
# ============================================

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "Target AWS region"
  default     = "us-east-1"
}

resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags = {
    Name        = "novapay-vpc"
    Environment = "production"
    ManagedBy   = "radcloud"
  }
}

resource "aws_subnet" "public" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.0.0/24"
  availability_zone       = "${var.aws_region}a"
  map_public_ip_on_launch = true

  tags = { Name = "novapay-public-a" }
}

resource "aws_subnet" "private_app" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.1.0/24"
  availability_zone = "${var.aws_region}a"

  tags = { Name = "novapay-private-app-a" }
}

resource "aws_subnet" "private_data" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.2.0/24"
  availability_zone = "${var.aws_region}a"

  tags = { Name = "novapay-private-data-a" }
}

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
  tags   = { Name = "novapay-igw" }
}

resource "aws_security_group" "web" {
  name_prefix = "novapay-web-"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "novapay-web-sg" }
}

resource "aws_security_group" "internal" {
  name_prefix = "novapay-internal-"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port   = 0
    to_port     = 65535
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/16"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "novapay-internal-sg" }
}
'''
    files.append({
        "path": "terraform/networking/main.tf",
        "description": "Target VPC, subnets, IGW, and security groups",
    })
    terraform_contents["terraform/networking/main.tf"] = networking_tf

    # --- Compute module ---
    compute_tf = '''# ============================================
# NovaPay AWS — Compute (EC2)
# Generated by RADCloud Watchdog Agent
# ============================================

data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"]  # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }
}

resource "aws_instance" "web_server_1" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "m5.xlarge"  # maps from n1-standard-4
  subnet_id              = var.public_subnet_id
  vpc_security_group_ids = [var.web_sg_id]

  root_block_device {
    volume_size = 100
    volume_type = "gp3"
  }

  tags = {
    Name        = "novapay-web-1"
    Environment = "production"
    Team        = "platform"
    App         = "web-frontend"
  }
}

resource "aws_instance" "web_server_2" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "m5.xlarge"
  subnet_id              = var.public_subnet_id
  vpc_security_group_ids = [var.web_sg_id]

  root_block_device {
    volume_size = 100
    volume_type = "gp3"
  }

  tags = {
    Name        = "novapay-web-2"
    Environment = "production"
    Team        = "platform"
    App         = "web-frontend"
  }
}

resource "aws_instance" "worker" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "r5.xlarge"  # maps from n1-highmem-4
  subnet_id              = var.private_app_subnet_id
  vpc_security_group_ids = [var.internal_sg_id]

  root_block_device {
    volume_size = 200
    volume_type = "gp3"
  }

  tags = {
    Name        = "novapay-worker"
    Environment = "production"
    Team        = "data"
    App         = "payment-processor"
  }
}

variable "public_subnet_id" {}
variable "private_app_subnet_id" {}
variable "web_sg_id" {}
variable "internal_sg_id" {}
'''
    files.append({
        "path": "terraform/compute/main.tf",
        "description": "EC2 instances mapped from GCP Compute Engine",
    })
    terraform_contents["terraform/compute/main.tf"] = compute_tf

    # --- Database module ---
    database_tf = '''# ============================================
# NovaPay AWS — Database (RDS PostgreSQL)
# Generated by RADCloud Watchdog Agent
# ============================================

resource "aws_db_subnet_group" "main" {
  name       = "novapay-db-subnet-group"
  subnet_ids = var.private_data_subnet_ids

  tags = { Name = "novapay-db-subnets" }
}

resource "aws_db_instance" "primary" {
  identifier              = "novapay-primary-db"
  engine                  = "postgres"
  engine_version          = "14"
  instance_class          = "db.m5.xlarge"  # maps from db-n1-standard-4
  allocated_storage       = 200
  storage_type            = "gp3"
  multi_az                = true  # maps from REGIONAL availability
  db_subnet_group_name    = aws_db_subnet_group.main.name
  vpc_security_group_ids  = [var.db_sg_id]
  backup_retention_period = 7
  storage_encrypted       = true
  skip_final_snapshot     = false

  parameter_group_name = aws_db_parameter_group.main.name

  tags = {
    Name        = "novapay-primary"
    Environment = "production"
  }
}

resource "aws_db_parameter_group" "main" {
  family = "postgres14"
  name   = "novapay-pg14"

  parameter {
    name  = "max_connections"
    value = "500"
  }
}

resource "aws_db_instance" "read_replica" {
  identifier             = "novapay-read-replica"
  replicate_source_db    = aws_db_instance.primary.identifier
  instance_class         = "db.m5.large"  # maps from db-n1-standard-2
  storage_type           = "gp3"
  vpc_security_group_ids = [var.db_sg_id]
  skip_final_snapshot    = true

  tags = {
    Name        = "novapay-replica"
    Environment = "production"
  }
}

variable "private_data_subnet_ids" { type = list(string) }
variable "db_sg_id" {}
'''
    files.append({
        "path": "terraform/database/main.tf",
        "description": "RDS PostgreSQL primary + read replica mapped from Cloud SQL",
    })
    terraform_contents["terraform/database/main.tf"] = database_tf

    # --- Observability / Budgets module ---
    observability_tf = '''# ============================================
# NovaPay AWS — Observability & Budgets
# Generated by RADCloud Watchdog Agent
# ============================================

resource "aws_cloudwatch_metric_alarm" "high_cpu_web" {
  alarm_name          = "novapay-high-cpu-web"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = 300
  statistic           = "Average"
  threshold           = 80
  alarm_description   = "Web server CPU above 80% for 10 minutes"
  alarm_actions       = [var.sns_topic_arn]

  dimensions = {
    AutoScalingGroupName = "novapay-web-asg"
  }
}

resource "aws_cloudwatch_metric_alarm" "rds_connections" {
  alarm_name          = "novapay-rds-connections"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  metric_name         = "DatabaseConnections"
  namespace           = "AWS/RDS"
  period              = 300
  statistic           = "Average"
  threshold           = 400
  alarm_description   = "RDS connections approaching max_connections (500)"
  alarm_actions       = [var.sns_topic_arn]

  dimensions = {
    DBInstanceIdentifier = "novapay-primary-db"
  }
}

resource "aws_budgets_budget" "monthly" {
  name         = "novapay-monthly-budget"
  budget_type  = "COST"
  limit_amount = "12000"
  limit_unit   = "USD"
  time_unit    = "MONTHLY"

  notification {
    comparison_operator        = "GREATER_THAN"
    threshold                  = 80
    threshold_type             = "PERCENTAGE"
    notification_type          = "FORECASTED"
    subscriber_email_addresses = ["finops@novapay.io"]
  }

  notification {
    comparison_operator        = "GREATER_THAN"
    threshold                  = 100
    threshold_type             = "PERCENTAGE"
    notification_type          = "ACTUAL"
    subscriber_email_addresses = ["finops@novapay.io"]
  }
}

variable "sns_topic_arn" {
  description = "SNS topic for alarm notifications"
  default     = ""
}
'''
    files.append({
        "path": "terraform/observability/main.tf",
        "description": "CloudWatch alarms and AWS Budgets for post-migration monitoring",
    })
    terraform_contents["terraform/observability/main.tf"] = observability_tf

    return {
        "format": "terraform",
        "mode": "generated_scaffold",
        "files": files,
        "terraform_contents": terraform_contents,
        "assumptions": [
            "us-east-1 target region",
            "Module-based layout with separate networking, compute, database, and observability",
            "Remote state in S3 (not configured — add backend block before apply)",
            "Ubuntu 22.04 LTS AMI for EC2 instances",
            "gp3 storage volumes (better price-performance than gp2)",
        ],
        "deployment_notes": (
            "Generated as a migration accelerator. Review all modules before production apply. "
            "Key TODOs: configure S3 backend for state, add NAT Gateway for private subnets, "
            "wire up variable references between modules, and add Route 53 hosted zone."
        ),
    }
